# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jonttamax
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: lambda-ts-project
# "service" is the name of this project. This will also be added to your AWS resource names.
service: lambda-ts-project

stages:
  default:
    params:
      tableName: "contact-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ContactsTable, Arn]
  environment:
    CONTACT_TABLE: ${param:tableName}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    ContactsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}
